export enum Screen {
  Home = "Home",
  Hub = "Hub",
  Join = "Join",
  Games = "Games",
  Spin = "Spin",
  Quiz = "Quiz",
  Dice = "Dice",
  Imposter = "Imposter",
  GameTypeList = "GameTypeList",
  GameList = "GameList",
  Admin = "Admin",
  Logs = "Logs",
  Profile = "Profile",
  EditProfile = "EditProfile",
  ChangePassword = "ChangePassword",
  SavedGames = "SavedGames",
  TipsUs = "TipsUs",
  Error = "Error",
  Problem = "Problem",
  Info = "Info",
  TipsList = "TipsList",
}

export default Screen;
